= Отчет по лабораторной работе №2
Анисимова А.М.    <КЭ-413>
:imagesdir: image
:toc:
:toc-title: Оглавление
:figure-caption: Рисунок
:table-caption: Таблица
:sectnums: |,all|





И так домашнее задание.
 
1.  Жду отчет по тому что выполняли из прошлой лекции + по лабе 1. Хочу там увидеть, следующее:
-  какие бывают типы?
-  почему нельзя типы смешивать между собой
- что такое неявное преобразование типов?
- что такое явное преобразование типов?
-  размеры типов
-  почему использование встроенных типов плохо?
- что такое явное преобразование типов?
-  какие функции преобразования бывают?
- как распределяется память ОЗУ в микроконтроллере?
- что такое указатель
- что можно делать с указателем
- как изменить любую ячейку памяти
-  если указатель типа Int указывает на адрес 1 и к этому указателю прибавит 1, то на какой адрес будет указывать указать и почему? А если указатель будет типа double
- если в ячейке по адресу 1 лежит число 10, в ячейке по адресу 2 лежит число 20, в ячейке по адресу 3 лежит число 30, в ячейке по адресу 4 лежит число 40 и если у нас указатель типа std::uint32_t указывает на адрес 1, то какое число будет в переменной b после разименовывания указателя?
std::uint32_t* ptr = reinterpret_cast<std::uin32_t>(1);
auto b = *ptr; //чему равно b?
 -  тоже самое условие  только теперь указатель на std::uin16_t
std::uint16_t* ptr = reinterpret_cast<std::uin16_t>(1);
auto b = *ptr; //чему равно b?
-  что такое регистр? Как поменять его значение
- что такое дизъюнкция  и конъюнкция
- как сбросить бит
 
 
2.
// auto b = "c";  //Задание на дом. Какого типа b?
 // auto b1 = 'c';  //Задание на дом. Какого типа b1?   
 // char a = 'A';  //Задание на дом, в какое число переведется символ А