= Отчет по лабораторной работе №3
Анисимова А.М.    <КЭ-413>
:imagesdir: images
:toc:
:toc-title: Оглавление
:figure-caption: Рисунок
:table-caption: Таблица
:sectnums: |,all|

== Введение

В этой лабораторной работе главной задачей было усовершенствование кода для легкого изменения его в последующем. 

Для этого мы использовали новый синтексис из ООП: класс и интерфейс. Также изменили метод включения и выключения диодов, используя методы внутри класса.


== Классы
Кроме использования встроенных типов, таких как int, double и т.д., мы можем определять свои собственные типы или классы. Класс представляет составной тип, который может использовать другие типы.

Класс предназначен для описания некоторого типа объектов. То есть по сути класс является планом объекта. А объект представляет конкретное воплощение класса, его реализацию. Можно еще провести следующую аналогию. У нас у всех есть некоторое представление о человеке, у которого есть имя, возраст, какие-то другие характеристики. То есть некоторый шаблон - этот шаблон можно назвать классом. Конкретное воплощение этого шаблона может отличаться, например, одни люди имеют одно имя, другие - другое имя. И реально существующий человек будет представлять объект или экземпляр этого класса.

Для определения класса применяется ключевое слово class, после которого идет имя класса:
----
class Led
{
    // компоненты класса
};
----
В данном случае класс называется Led. Как правило, названия классов начинаются с большой буквы. Допустим, данные класс представляет диод. Данный класс пуст, не содержит никаких компонентов, тем не менее он уже представляет новый тип. И после определения класса мы можем определять его переменные или константы:

----
class Led
{
public:
    Led(std::uint32_t registrAddress, std::uint32_t pinNumber) :
    registrAddr(registrAddress),
    pinNum(pinNumber)
    {
    }

    void Light()
    {
        GPIOC::ODR::Set(1 « pinNum);
    }
    
private:
    std::uint32_t registrAddr;
    std::uint32_t pinNum;
};
----
Теперь класс Led имеет:



* Публичные члены (public):

. Конструктор Led(std::uint32_t registrAddress, std::uint32_t pinNumber); 

    Конструктор принимает два параметра:

    *registrAddress: адрес регистра, связанного с пином, на котором подключён светодиод.

    *pinNumber: номер пина, который используется для управления светодиодом.
    Внутри конструктора эти значения сохраняются в приватные члены registrAddr и pinNum.


. Метод Light

    Этот метод включает светодиод, устанавливая бит, соответствующий pinNum, в регистре данных выхода (ODR).


* Приватные члены (private):

. std::uint32_t registrAddr – Хранит адрес регистра (например, базовый адрес порта), связанного с пином, к которому подключен светодиод.

. std::uint32_t pinNum – Хранит номер пина, который используется для управления светодиодом.


== Интерфейсы
Интерфейсы реализуются через абстрактные классы, содержащие чисто виртуальные функции. Интерфейсы предоставляют абстрактный набор методов, которые классы должны реализовать. Это обеспечивает структурную однородность в приложении, позволяя разным классам предоставлять общий интерфейс.

Интерфейс/интерфейсный класс/абстрактный класс:

----
class ILed
{
public:
    virtual void Light();
};
----

В данном примере Light() является чисто виртуальной функцией, что делает класс ILed интерфейсом. Интерфейсы не могут создавать экземпляры.

Реализация интерфейса в классе:
----
class Led : public ILed
{
public:    
    void Light()
    {
        GPIOC::ODR::Set(1 « pinNum);
    }
};
----

Класс Led наследует от интерфейса ILed и предоставляет реализацию метода Light().

== Отличие интерфейсов от классов в С++

* Множественное наследование интерфейсов: Классы могут наследовать от нескольких интерфейсов, предоставляя реализации для всех соответствующих методов.

* Интерфейсы как контракты: Использование интерфейсов обеспечивает ясные контракты между разными частями программы, улучшая читаемость и обеспечивая однородность в структуре приложения.




== Итоговый результат лабораторной №3

Благодаря улучшению кода мы всегда можем внести новые диоды, которыми нужно управлять и слегкостью заменить порядок включения и выключения.

----
#include "rccregisters.hpp" // for RCC
#include "gpioaregisters.hpp" // for GPIOA
#include "gpiocregisters.hpp" // for GPION
#include <array> // for array


std::uint32_t SystemCoreClock = 16'000'000U;

extern "C" {
    int __low_level_init(void)
    {
        //Switch on external 16 MHz oscillator
        RCC::CR::HSION::On::Set();
        while (RCC::CR::HSIRDY::NotReady::IsSet())
        {

        }
        //Switch system clock on external oscillator
        RCC::CFGR::SW::Hsi::Set();
        while (!RCC::CFGR::SWS::Hsi::IsSet())
        {

        }

        RCC::APB2ENR::SYSCFGEN::Enable::Set();

        return 1;
    }
}

void delay(int cycles)
{
for(int i = 0; i < cycles; ++i)
{
    //asm volatile("");
}
}

class ILed
{
public:
    virtual void Light();
    virtual void Off();
    virtual void Toggle();
};

class Led : public ILed
{
public:
    Led(std::uint32_t registrAddress, std::uint32_t pinNumber) :
    registrAddr(registrAddress),
    pinNum(pinNumber)
    {
    }

    void Light()
    {
        GPIOC::ODR::Set(1 « pinNum);
    }
    void Toggle()
    {
        GPIOC::ODR::Toggle(1 « pinNum);
    }
private:
    std::uint32_t registrAddr;
    std::uint32_t pinNum;
};


int main()
{
    RCC::AHB1ENR::GPIOAEN::Enable::Set();
    RCC::AHB1ENR::GPIOCEN::Enable::Set();
    GPIOA::MODER::MODER5::Output::Set();
    GPIOC::MODER::MODER5::Output::Set();
    GPIOC::MODER::MODER8::Output::Set();
    GPIOC::MODER::MODER9::Output::Set();

    constexpr std::uint32_t gpiocOdrRegAddres = 0x40020814U;
    constexpr std::uint32_t gpioaOdrRegAddres = 0x40020014U;

    Led led1(gpiocOdrRegAddres, 5);
    Led led2(gpiocOdrRegAddres, 8);
    Led led3(gpiocOdrRegAddres, 9);
    Led led4(gpioaOdrRegAddres, 5);

    std::array<Led*, 10> leds = {
    &led1,
    &led2,
    &led3};


        for (;;){

        for(auto it: leds){
            it -> Toggle();
            delay(800000);
        }
    }

    return 1;
}
----